spring:
   datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: testproject3.cptggcrmj2t4.us-east-2.rds.amazonaws.com
      username: john
      password: password
   jpa:
     hibernate:
       show-sql: true
       
server.servlet.contextPath: /CMSforce