spring:
   datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@primaveradb.cyysbedq8cqc.us-east-1.rds.amazonaws.com:1521:ORCL
      username: adam
      password: primavera##
   jpa:
     hibernate:
       show-sql: true
       
server.servlet.contextPath: /CMSforce