       
spring:
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@testproject3.cptggcrmj2t4.us-east-2.rds.amazonaws.com:1521:ORCL
      username: john
      password: password
  jpa:
     hibernate:
       show-sql: true
       
logging:  config:
  file: src/main/resources/exampleLog.log
  
  
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:   
    org.springframework.web: ERROR
    com.revature: DEBUG
    org.hibernate: ERROR
       
server.servlet.contextPath: /CMSforce



  
          
      


      
